"""数据库模块初始化"""
from .models import (
    Base,
    Camera,
    Detection,
    DetectionStatistics,
    SystemEvent,
    Alert,
    User,
    Settings
)
from .extended_models import (
    ActionSegment,
    ActionSequence,
    ScrewDetection,
    MaterialPick,
    PostureEvent,
    FatigueRecord,
    SensorReading,
    WorkflowStep,
    WorkflowExecution,
    TrainingData
)
from .manager import (
    DatabaseManager,
    get_db_manager,
    get_db,
    init_database,
    reset_database
)
from .repositories import (
    CameraRepository,
    DetectionRepository,
    AlertRepository,
    UserRepository,
    SettingsRepository
)
from .extended_repositories import (
    ActionSegmentRepository,
    ScrewDetectionRepository,
    MaterialPickRepository,
    PostureEventRepository,
    FatigueRecordRepository,
    SensorReadingRepository
)

__all__ = [
    "Base",
    "Camera",
    "Detection",
    "DetectionStatistics",
    "SystemEvent",
    "Alert",
    "User",
    "Settings",
    "ActionSegment",
    "ActionSequence",
    "ScrewDetection",
    "MaterialPick",
    "PostureEvent",
    "FatigueRecord",
    "SensorReading",
    "WorkflowStep",
    "WorkflowExecution",
    "TrainingData",
    "DatabaseManager",
    "get_db_manager",
    "get_db",
    "init_database",
    "reset_database",
    "CameraRepository",
    "DetectionRepository",
    "AlertRepository",
    "UserRepository",
    "SettingsRepository",
    "ActionSegmentRepository",
    "ScrewDetectionRepository",
    "MaterialPickRepository",
    "PostureEventRepository",
    "FatigueRecordRepository",
    "SensorReadingRepository"
]
